{{ if eq .Values.Networking.ServiceType "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.Networking.Hostname }}
    {{- with .Values.ServiceAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: htcondor-ce
    port: 9619
    targetPort: htcondor-ce
    protocol: TCP
  {{ if .Values.Networking.RequestIP }}
  loadBalancerIP: {{ .Values.Networking.RequestIP }}
  {{ end }}
  selector:
    app: {{ template "osg-hosted-ce.name" . }}
    instance: {{ .Values.Instance }}
{{ end }}
